const ELEMENT_STATE = {
  PRESENT: 'PRESENT',
  EXISTS: 'EXISTS',
  ABSENT: 'ABSENT',
  NOT_VISIBLE: 'NOT VISIBLE',
  NOT_EXISTS: 'NOT EXISTS',
  ENABLED: 'ENABLED',
};

module.exports = ELEMENT_STATE;
